### PR TITLE
made it only due dates

### PR DESCRIPTION
**Pull request by FengqiuAdamDong**

### CODE REVIEW

**Comment by FengqiuAdamDong** [comment]
merged!

**Comment by FengqiuAdamDong** [comment]
I fixed all issues with python 3 integration and also made it so that it only syncs tasks with due dates so that habitica doesn't get flooded

**Comment by mchlnix** [comment]
Thanks for the contribution. I also just noticed, that you removed the shell script. No worries, those were all test accounts, I lost the credentials to, anyway.

I don't use habitica anymore, unfortunately. So I hope it still works :)

**Comment by FengqiuAdamDong** [comment]
It still works well! thank you for writing the code! I am using it daily now so will do my best to maintain the software

**Pull request merged**
